routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Auth::check()){
    	return redirect()->route('dashboard-index');
	}
	else{
		return redirect()->route('login');
	}
});
Route::get('/form', 'StudentDirectoryController@guest_create')->name('guest_create');
Route::post('/form', 'StudentDirectoryController@guest_save')->name('guest_save');
Route::get('/response', 'StudentDirectoryController@responsepage')->name('guest_response');
Auth::routes();
Route::middleware('auth')->group(function () {
Route::middleware('appex')->group(function () {
	Route::resource('/systems/users', 'UserController');
    Route::resource('/systems/roles', 'RoleController');
    Route::resource('/systems/permissions', 'RoleController');
    Route::resource('/systems/settings', 'RoleController');
    Route::get('/systems/users/print/list','UserController@printall')->name('user-print');
    Route::get('/systems/profile', 'UserController@profile')->name('profile');
    Route::post('/systems/profile', 'UserController@updateProfile')->name('update-profile');
    Route::get('/systems/logs','UserController@logs_index')->name('logs.index');
    Route::get('/systems/logs/print','UserController@log_print')->name('logs.print');

    Route::get('/directory/{id}', 'StudentDirectoryController@index')->name('directory-index');
    Route::get('/directory/printall/{id}', 'StudentDirectoryController@printall')->name('directory-printall');
    Route::get('/directory/printid/{id}', 'StudentDirectoryController@print_id')->name('directory-print_id');
    Route::get('/directory/{id}/print/{ref_id}', 'StudentDirectoryController@print_each')->name('directory-print_each');
    Route::get('/directory/{id}/create', 'StudentDirectoryController@create')->name('directory-create');
    Route::post('/directory/{id}/create', 'StudentDirectoryController@store')->name('directory-store');
    Route::get('/directory/{id}/edit/{ref_id}', 'StudentDirectoryController@edit')->name('directory-edit');
    Route::post('/directory/{id}/edit/{ref_id}', 'StudentDirectoryController@update')->name('directory-update');

    Route::resource('/settings/courses','CoursesController');
    Route::get('/settings/courses/print/list','CoursesController@printall')->name('courses-print');


	Route::get('/search', 'HomeController@getsearch_global')->name('search-display');
	Route::get('/courses/notification/show', 'HomeController@notification')->name('notify-display');

    Route::get('/home', 'HomeController@index')->name('dashboard-index');
    Route::get('/untrack/recent', 'HomeController@recent')->name('recent-list');
    Route::post('/untrack/recent', 'HomeController@profileMany')->name('recent-many');
    Route::delete('/untrack/recent/{id}', 'HomeController@remove')->name('recent-remove');
    Route::put('/untrack/recent/{id}', 'HomeController@update')->name('recent-update');
    Route::get('/untrack/view_profile/{id}', 'HomeController@view_profile')->name('recent-view');
    Route::post('/untrack/view_profile/{id}', 'HomeController@profile')->name('recent-profile');
    Route::get('/untrack/mark/', 'HomeController@mark')->name('recent-mark');
    Route::get('/untrack/notify/btn', 'HomeController@btnnotify')->name('recent-notify');
    Route::get('/settings/sy/index', 'SchoolYearController@index')->name('sy.index');
    Route::get('/settings/sy/create', 'SchoolYearController@create')->name('sy.create');
    Route::post('/settings/sy/create', 'SchoolYearController@store')->name('sy.store');
    Route::get('/settings/sy/{id}', 'SchoolYearController@edit')->name('sy.edit');
    Route::patch('/settings/sy/{id}', 'SchoolYearController@update')->name('sy.update');

    Route::get('/search', 'HomeController@getsearch_global')->name('search');
});
});
Route::get('/places/provinces', 'PlacesController@getprovinces')->name('provinces');
Route::get('/places/citymun', 'PlacesController@getcitymun')->name('citymun');
Route::get('/places/barangays', 'PlacesController@getbarangays')->name('barangays');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends \Spatie\Permission\Models\Role
{
    //
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Authorizable;
use App\Permission;
use App\Role;
use Illuminate\Http\Request;
use App\TabMenu;
use App\GuestPermission;
use App\SystemLog;
use Auth;
class RoleController extends Controller
{
    use Authorizable;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        $menus = TabMenu::all();

        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Roles';
        $log->user_id = Auth::user()->id;
        $log->action = 'View';
        $log->save();
        
        return view('role.index', compact('roles', 'menus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['name' => 'required|unique:roles']);

        if( Role::create($request->only('name')) ) {
            $request->session()->flash('alert-success', 'Role Added.');
            return redirect()->route('roles.index');
        }
        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Roles';
        $log->user_id = Auth::user()->id;
        $log->action = 'Store';
        $log->save();
        return redirect()->back();
    }

    public function edit($id){
        if($id == 0){
            $role = (object)['name' => 'Guest'];
        }
        else{
            $role = Role::findOrFail($id);
            if(!$role){
                abort(404);
            }
        }
        $menus = TabMenu::all();

        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Roles';
        $log->user_id = Auth::user()->id;
        $log->action = 'Edit Roles';
        $log->save();

        return view('role.edit', compact('role', 'menus'));
    }

    public function show($id){
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Roles';
        $log->user_id = \Auth::user()->id;
        $log->action = 'View';
        $log->save();
        return $this->edit($id);
    }

    public function create(){
        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Roles';
        $log->user_id = Auth::user()->id;
        $log->action = 'Create New';
        $log->save();
        return view('role.new');
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($id == 0){
            $guest = GuestPermission::first();
            $guest->form = ($request->input('guestform')) ? 'Yes' : 'No';
            $guest->register = ($request->input('guestregister')) ? 'Yes' : 'No';
            $guest->save();
            $request->session()->flash('alert-success', 'Guest permissions has been updated.');
        }
        else{
            if($role = Role::findOrFail($id)) {
                // admin role has everything
                if($role->name === 'Admin') {
                    $role->syncPermissions(Permission::all());
                    return redirect()->route('roles.index');
                }

                $permissions = $request->get('permissions', []);

                $role->syncPermissions($permissions);

                $request->session()->flash('alert-success', $role->name . ' permissions has been updated.');
            } else {
                $request->session()->flash('alert-danger', 'Role with id '. $id .' note found.');
            }
        }
        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Roles';
        $log->user_id = Auth::user()->id;
        $log->action = 'Update';
        $log->save();
        return redirect()->route('roles.index');
    }
}

resources/views/role/edit.blade.php
@extends('layouts.master')
@section('title', ' - Roles')
@section('content_header', $role->name . ' Role')
@section('content_header_link')
    @can('view_roles')
        <li class="breadcrumb-item active"><a href="{{ route('roles.index') }}">System Roles</a></li>
    @endcan
    @can('add_roles')
        <li class="breadcrumb-item "><a href="{{ route('roles.create') }}">Create Roles</a></li>
    @endcan
@endsection
@section('content')
    <div class="card pd-20 pd-sm-40" style="min-height: 450px;">
        @if ($role->name != 'Guest')
            <div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
            <div class="card">
                <div class="card-header" role="tab" id="heading{{$role->id}}">
                    <h6 class="mg-b-0">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{$role->id}}" aria-expanded="true" aria-controls="collapse{{$role->id}}" class="tx-gray-800 transition">
                            {{$role->name}}
                        </a>
                    </h6>
                </div>
                <div id="collapse{{$role->id}}" class="collapse show" role="tabpanel" aria-labelledby="heading{{$role->id}}">
                    <div class="card-body">
                        <form action="{{ route('roles.update',$role->id) }}" method="POST" name="edit-role" id="edit-role">
                        {{ method_field('PUT') }}
                        {{csrf_field()}}
                        <div class="row">
                             @foreach($menus as $menu)
                                <div class="col-sm-3">
                                    <fieldset style="min-height: 200px">
                                        <legend>
                                            {{ucfirst($menu->name)}}
                                        </legend>
                                        <div class="form-layout">
                                            <div class="row mg-b-5">
                                                @foreach($menu->crop() as $k => $perm)
                                                    <?php
                                                        $per_found = null;

                                                        if( isset($role) ) {
                                                            $per_found = $role->hasPermissionTo($perm->name);
                                                        }

                                                        if( isset($user)) {
                                                            $per_found = $user->hasDirectPermission($perm->name);
                                                        }
                                                        $permname = explode('_', $perm->name)
                                                    ?>
                                                    <div class="col-sm-12">
                                                        <label class="{{ str_contains($perm->name, 'delete') ? 'text-danger' : '' }}">
                                                            <input type="checkbox" class="js-switch" data-color="#009efb" data-size="small" name="permissions[]" {{($per_found) ? 'checked' : ''}} value="{{$perm->name}}"/>
                                                            {{ ucfirst($permname[0]) }} {{-- ucfirst($permname[1]) --}}
                                                        </label>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>
                            @endforeach
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <hr/>
                                @can('edit_roles')
                                    <button type="submit" class="pull-right btn btn-default btn-sm" form="edit-role">
                                        Update
                                    </button>
                                @endcan
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        @else
            <form action="{{ route('roles.update',0) }}" method="POST" name="edit-role" id="edit-role">
                {{ method_field('PUT') }}
                        {{csrf_field()}}
            <div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
                <div class="card">
                    <div class="card-header" role="tab" id="heading0">
                        <h6 class="mg-b-0">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0" class="tx-gray-800 transition">
                                Guest
                            </a>
                        </h6>
                    </div>
                    <div id="collapse0" class="collapse show" role="tabpanel" aria-labelledby="heading0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <fieldset>
                                        <legend>
                                            Guest Permission
                                        </legend>
                                        <div class="form-layout">
                                            <div class="row mg-b-5">
                                                <div class="col-sm-12">
                                                    <label>
                                                        <input type="checkbox" class="js-switch" data-color="#009efb" data-size="small" name="guestform" {{(App\GuestPermission::get_guest()->form == 'Yes') ? 'checked' : ''}} value="{{App\GuestPermission::get_guest()->form}}"/>
                                                        Allow Form
                                                    </label>
                                                </div>
                                                <div class="col-sm-12">
                                                    <label>
                                                        <input type="checkbox" class="js-switch" data-color="#009efb" data-size="small" name="guestregister" {{(App\GuestPermission::get_guest()->register == 'Yes') ? 'checked' : ''}} value="{{App\GuestPermission::get_guest()->register}}"/>
                                                        Allow Register
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <hr/>
                                    @can('edit_roles')
                                        <button type="submit" class="pull-right btn btn-default btn-sm" form="edit-role">
                                            Update
                                        </button>
                                    @endcan
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        @endif
    </div>
    @push('append_css')
        <link rel="stylesheet" href="{{ asset('assets/lib/switchery/dist/switchery.min.css') }}">
    @endpush

    @push('append_js')
        <script src="{{ asset('assets/lib/switchery/dist/switchery.min.js') }}"></script>
        <script type="text/javascript">
            var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
            elems.forEach(function(html) {
              var switchery = new Switchery(html,{ size: 'small' });
            });
        </script>
    @endpush
@endsection

resources/views/role/guest.blade.php
            <div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
                <div class="card">
                    <div class="card-header" role="tab" id="heading0">
                        <h6 class="mg-b-0">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0" class="tx-gray-800 transition">
                                Guest
                            </a>
                        </h6>
                    </div>
                    <div id="collapse0" class="collapse show" role="tabpanel" aria-labelledby="heading0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <fieldset>
                                        <legend>
                                            Guest Permission
                                        </legend>
                                        <div class="form-layout">
                                            <div class="row mg-b-5">
                                                <div class="col-sm-12">
                                                    <label>
                                                        <input type="checkbox" class="js-switch" data-color="#009efb" data-size="small" name="guest[]" disabled="" {{(App\GuestPermission::get_guest()->form == 'Yes') ? 'checked' : ''}} value="{{App\GuestPermission::get_guest()->form}}"/>
                                                        Allow Form
                                                    </label>
                                                </div>
                                                <div class="col-sm-12">
                                                    <label>
                                                        <input type="checkbox" class="js-switch" data-color="#009efb" data-size="small" name="guest[]" disabled="" {{(App\GuestPermission::get_guest()->register == 'Yes') ? 'checked' : ''}} value="{{App\GuestPermission::get_guest()->register}}"/>
                                                        Allow Register
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <hr/>
                                        @can('edit_roles')
                                            <a href="{{ route('roles.edit', 0) }}" class="pull-right btn btn-info btn-sm">
                                                Edit
                                            </a>
                                        @endcan
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

resources/views/role/index.blade.php
@extends('layouts.master')
@section('title', ' - Roles')
@section('content_header', 'Roles')
@section('content_header_link')
    <li class="breadcrumb-item active">System Roles</li>
    @can('add_roles')
        <li class="breadcrumb-item "><a href="{{ route('roles.create') }}">Create Roles</a></li>
    @endcan
@endsection
@section('content')
    <div class="card pd-20 pd-sm-40" style="min-height: 450px;">
        @include('shared._alert')
        <h6 class="card-body-title">List</h6>
        <p class="mg-b-10 mg-sm-b-10">List of user's role.</p>
        {{-- @include('role.guest') --}}
        @forelse ($roles as $k => $role)
            <div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
                <div class="card">
                    <div class="card-header" role="tab" id="heading{{$role->id}}">
                        <h6 class="mg-b-0">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{$role->id}}" aria-expanded="true" aria-controls="collapse{{$role->id}}" class="tx-gray-800 transition">
                                {{$role->name}}
                            </a>
                        </h6>
                    </div>
                    <div id="collapse{{$role->id}}" class="collapse show" role="tabpanel" aria-labelledby="heading{{$role->id}}">
                        <div class="card-body">
                            <div class="row">
                                @foreach($menus as $menu)
                                    @if($menu->filter != "_untrack")
                                    <div class="col-sm-3">
                                        <fieldset style="min-height: 200px">
                                            <legend>
                                                {{ucfirst($menu->name)}}
                                            </legend>
                                            <div class="form-layout">
                                                <div class="row mg-b-5">
                                                    @foreach($menu->crop() as $k => $perm)
                                                        <?php
                                                            $per_found = null;

                                                            if( isset($role) ) {
                                                                $per_found = $role->hasPermissionTo($perm->name);
                                                            }

                                                            if( isset($user)) {
                                                                $per_found = $user->hasDirectPermission($perm->name);
                                                            }
                                                            $permname = explode('_', $perm->name)
                                                        ?>
                                                        <div class="col-sm-12">
                                                            <label class="{{ str_contains($perm->name, 'delete') ? 'text-danger' : '' }}">
                                                                <input type="checkbox" class="js-switch" data-color="#009efb" data-size="small" name="permissions[]" disabled="" {{($per_found) ? 'checked' : ''}} value="{{$perm->name}}"/>
                                                                {{ ucfirst($permname[0]) }} {{-- ucfirst($permname[1]) --}}
                                                            </label>
                                                        </div>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </fieldset>
                                    </div>
                                    @endif
                                @endforeach
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <hr/>
                                    @if($role->name != "Admin")
                                        @can('edit_roles')
                                            <a href="{{ route('roles.edit',$role->id) }}" class="pull-right btn btn-info btn-sm">
                                                Edit
                                            </a>
                                        @endcan
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @empty
        
        @endforelse
    </div>
    @push('append_css')
        <link rel="stylesheet" href="{{ asset('assets/lib/switchery/dist/switchery.min.css') }}">
    @endpush

    @push('append_js')
        <script src="{{ asset('assets/lib/switchery/dist/switchery.min.js') }}"></script>
        <script type="text/javascript">
            var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
            elems.forEach(function(html) {
              var switchery = new Switchery(html,{ size: 'small' });
            });
        </script>
    @endpush
@endsection

resources/views/role/new.blade.php
@extends('layouts.master')
@section('title', ' - Roles')
@section('content_header', 'Create Roles')
@section('content_header_link')
    @can('view_roles')
        <li class="breadcrumb-item active"><a href="{{ route('roles.index') }}">System Roles</a></li>
    @endcan
    <li class="breadcrumb-item active">Create Roles</li>
@endsection

@section('content')
<div class="card pd-20 pd-sm-40" style="min-height: 450px;">
    <form class="form-horizontal" action="{{route('roles.store')}}" method="POST">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row {{ $errors->has('name') ? ' has-error' : '' }}">
                    <label class="control-label text-right col-sm-4" for="name">Role Name:</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control form-control-sm" id="name" placeholder="Name" required name="name" value="{{ old('name') }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row ">
                    <label class="control-label text-right col-sm-4"></label>
                    <div class="col-md-8">
                        @can('add_roles')
                            <button type="submit" class="btn btn-sm btn-default btn-sm">
                                Save
                            </button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection