routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Auth::check()){
    	return redirect()->route('dashboard-index');
	}
	else{
		return redirect()->route('login');
	}
});
Route::get('/form', 'StudentDirectoryController@guest_create')->name('guest_create');
Route::post('/form', 'StudentDirectoryController@guest_save')->name('guest_save');
Route::get('/response', 'StudentDirectoryController@responsepage')->name('guest_response');
Auth::routes();
Route::middleware('auth')->group(function () {
Route::middleware('appex')->group(function () {
	Route::resource('/systems/users', 'UserController');
    Route::resource('/systems/roles', 'RoleController');
    Route::resource('/systems/permissions', 'RoleController');
    Route::resource('/systems/settings', 'RoleController');
    Route::get('/systems/users/print/list','UserController@printall')->name('user-print');
    Route::get('/systems/profile', 'UserController@profile')->name('profile');
    Route::post('/systems/profile', 'UserController@updateProfile')->name('update-profile');
    Route::get('/systems/logs','UserController@logs_index')->name('logs.index');
    Route::get('/systems/logs/print','UserController@log_print')->name('logs.print');

    Route::get('/directory/{id}', 'StudentDirectoryController@index')->name('directory-index');
    Route::get('/directory/printall/{id}', 'StudentDirectoryController@printall')->name('directory-printall');
    Route::get('/directory/printid/{id}', 'StudentDirectoryController@print_id')->name('directory-print_id');
    Route::get('/directory/{id}/print/{ref_id}', 'StudentDirectoryController@print_each')->name('directory-print_each');
    Route::get('/directory/{id}/create', 'StudentDirectoryController@create')->name('directory-create');
    Route::post('/directory/{id}/create', 'StudentDirectoryController@store')->name('directory-store');
    Route::get('/directory/{id}/edit/{ref_id}', 'StudentDirectoryController@edit')->name('directory-edit');
    Route::post('/directory/{id}/edit/{ref_id}', 'StudentDirectoryController@update')->name('directory-update');

    Route::resource('/settings/courses','CoursesController');
    Route::get('/settings/courses/print/list','CoursesController@printall')->name('courses-print');


	Route::get('/search', 'HomeController@getsearch_global')->name('search-display');
	Route::get('/courses/notification/show', 'HomeController@notification')->name('notify-display');

    Route::get('/home', 'HomeController@index')->name('dashboard-index');
    Route::get('/untrack/recent', 'HomeController@recent')->name('recent-list');
    Route::post('/untrack/recent', 'HomeController@profileMany')->name('recent-many');
    Route::delete('/untrack/recent/{id}', 'HomeController@remove')->name('recent-remove');
    Route::put('/untrack/recent/{id}', 'HomeController@update')->name('recent-update');
    Route::get('/untrack/view_profile/{id}', 'HomeController@view_profile')->name('recent-view');
    Route::post('/untrack/view_profile/{id}', 'HomeController@profile')->name('recent-profile');
    Route::get('/untrack/mark/', 'HomeController@mark')->name('recent-mark');
    Route::get('/untrack/notify/btn', 'HomeController@btnnotify')->name('recent-notify');
    Route::get('/settings/sy/index', 'SchoolYearController@index')->name('sy.index');
    Route::get('/settings/sy/create', 'SchoolYearController@create')->name('sy.create');
    Route::post('/settings/sy/create', 'SchoolYearController@store')->name('sy.store');
    Route::get('/settings/sy/{id}', 'SchoolYearController@edit')->name('sy.edit');
    Route::patch('/settings/sy/{id}', 'SchoolYearController@update')->name('sy.update');

    Route::get('/search', 'HomeController@getsearch_global')->name('search');
});
});
Route::get('/places/provinces', 'PlacesController@getprovinces')->name('provinces');
Route::get('/places/citymun', 'PlacesController@getcitymun')->name('citymun');
Route::get('/places/barangays', 'PlacesController@getbarangays')->name('barangays');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname','lastname', 'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use App\Permission;
use App\Authorizable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PDF;
use Hash;
use App\SystemLog;
class UserController extends Controller
{
    use Authorizable;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(){
        $this->page_num = 15;
    }

    public function index()
    {
        $result = User::latest()->paginate($this->page_num);
        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'View';
        $log->save();
        return view('user.index', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::select('name', 'id')->get();
        
        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'Create New';
        $log->save();

        return view('user.new', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'firstname' => 'required|min:1',
            'lastname' => 'required|min:1',
            'username' => 'required|unique:users',
            'password' => 'required|min:4',
            'roles' => 'required|min:1'
        ]);

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ( $user = User::create($request->except('roles', 'permissions')) ) {

            $this->syncPermissions($request, $user);

            $request->session()->flash('alert-success', 'User has been created.');

        } else {
            $request->session()->flash('alert-danger', 'Unable to create user.');
        }

        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'Store';
        $log->save();

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all('name', 'id');
        $permissions = Permission::all('name', 'id');
        $user_role = $user->roles->pluck('id')->toArray();

        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'Edit';
        $log->save();

        return view('user.edit', compact('user', 'roles', 'permissions','user_role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'firstname' => 'required|min:1',
            'lastname' => 'required|min:1',
            'username' => 'required|unique:users,username,' . $id,
            'roles' => 'required|min:1',
            'password' => 'required|string|min:4|confirmed'
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password','oldpassword'));

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        // Handle the user roles
        $this->syncPermissions($request, $user);

        $user->save();

        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'Update';
        $log->save();

        $request->session()->flash('alert-success', 'User has been updated.');

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @internal param Request $request
     */
    public function destroy(Request $request,$id)
    {
        if ( Auth::user()->id == $id ) {
            $request->session()->flash('alert-warning', 'Deletion of currently logged in user is not allowed :(');
            return redirect()->back();
        }

        if( User::findOrFail($id)->delete() ) {
            $request->session()->flash('alert-success', 'User has been deleted.');
        } else {
            $request->session()->flash('alert-warning', 'User not deleted.');
        }

        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'Delete';
        $log->save();

        return redirect()->back();
    }

    /**
     * Sync roles and permissions
     *
     * @param Request $request
     * @param $user
     * @return string
     */
    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);

        return $user;
    }

    public function printall(){
        if(!auth()->user()->can('print_users')){
            abort(403);
        }
        $users = User::all();

        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'Print All';
        $log->save();

        $pdf = PDF::setPaper("letter");
        $pdf->loadView('user.print',compact('users'));
        return $pdf->stream();
    }

    public function profile(){
        $user = auth()->user();
        
        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'View Profile';
        $log->save();

        return view('profile',compact('user'));
    }

    public function updateProfile(Request $request){
        $u = auth()->user();
        $user = User::findOrFail($u->id);

        if($request->input('update_photo')){
            if($request->hasFile('photo')){
                $photoName = time().'.'.$request->photo->getClientOriginalExtension();
                $request->photo->move(public_path('assets/images/users'), $photoName);
                $user->photo = $photoName;
                $user->save();
                $request->session()->flash('alert-success', 'User has been Updated.');
            }
        }
        else{
            if($request->hasFile('photo')){
                $photoName = time().'.'.$request->photo->getClientOriginalExtension();
                $request->photo->move(public_path('assets/images/users'), $photoName);
                $user->photo = $photoName;
            }

            if(Hash::check($request->input('oldpassword'), $user->password)){
                $user->username = $request->input('username');
                $user->password = bcrypt($request->input('newpassword'));
                $user->firstname = $request->input('firstname');
                $user->middlename = $request->input('middlename');
                $user->lastname = $request->input('lastname');
                $user->contact_number = $request->input('contact_number');
                $user->save();
                $request->session()->flash('alert-success', 'User has been Updated.');
            }
            else{
                $request->session()->flash('alert-danger', 'Something went wrong. Try again');
            }
        }
        $log = new SystemLog;
        $log->main_tab = 'User Management';
        $log->sub_tab = 'Users';
        $log->user_id = Auth::user()->id;
        $log->action = 'Update';
        $log->save();

        return redirect()->back();
    }

    public function logs_index(Request $request){
        if($request->input('filter')){
            $logs = SystemLog::where('user_id',$request->input('filter'))->orderBy('id','desc')->paginate(15);
        }
        else{
             $logs = SystemLog::orderBy('id','desc')->paginate(15);
        }
        $fid = $request->input('filter');
        $log = new SystemLog;
        $log->main_tab = 'System Properties';
        $log->sub_tab = 'Logs';
        $log->user_id = Auth::user()->id;
        $log->action = 'View';
        $log->save();
        return view('logs.index',compact('logs','fid'));
    }

    public function log_print(){
        $data = SystemLog::all();

        $log = new SystemLog;
        $log->main_tab = 'System Properties';
        $log->sub_tab = 'Logs';
        $log->user_id = Auth::user()->id;
        $log->action = 'Print';
        $log->save();

        $pdf = PDF::setPaper("letter");

resources/views/user/_form.blade.php
{{ csrf_field() }}
<div class="row">
    <div class="col-md-6">
        <div class="form-group row ">
            <label class="control-label text-right col-sm-4" for="firstname">First Name:</label>
            <div class="col-md-8">
                <input type="text" class="form-control form-control-sm {{ $errors->has('firstname') ? ' is-invalid' : '' }}" id="firstname" placeholder="First Name" required name="firstname" value="{{ isset($user) ? $user->firstname : old('firstname') }}">
                @if ($errors->has('firstname'))
                    <span class="help-block">
                        <strong>{{ $errors->first('firstname') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group row ">
            <label class="control-label text-right col-sm-4" for="lastname">Last Name:</label>
            <div class="col-md-8">
                <input type="text" class="form-control form-control-sm {{ $errors->has('lastname') ? ' is-invalid' : '' }}" id="lastname" placeholder="Last Name" required name="lastname" value="{{ isset($user) ? $user->lastname : old('lastname') }}">
                @if ($errors->has('lastname'))
                    <span class="help-block">
                        <strong>{{ $errors->first('lastname') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group row ">
            <label class="control-label text-right col-sm-4" for="username">Username:</label>
            <div class="col-md-8">
                <input type="text" class="form-control form-control-sm {{ $errors->has('username') ? ' is-invalid' : '' }}" id="username" name="username" placeholder="Username" required value="{{ isset($user) ? $user->username : old('username') }}">
                @if ($errors->has('username'))
                    <span class="help-block">
                        <strong>{{ $errors->first('username') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>
</div>
@if(isset($user))
    <div class="row">
        <div class="col-md-6">
            <div class="form-group row ">
                <label class="control-label text-right col-sm-4" for="oldpassword">Old Password:</label>
                <div class="col-md-8">
                    <input type="password" class="form-control form-control-sm  {{ $errors->has('oldpassword') ? ' is-invalid' : '' }}" id="oldpassword" placeholder="Current Password" name="oldpassword" required>
                    @if ($errors->has('oldpassword'))
                        <span class="help-block">
                            <strong>{{ $errors->first('oldpassword') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endif
<div class="row">
    <div class="col-md-6">
        <div class="form-group row ">
            <label class="control-label text-right col-sm-4" for="password">{{isset($user) ? 'New' : ''}} Password:</label>
            <div class="col-md-8">
                <input type="password" class="form-control form-control-sm {{ $errors->has('password') ? ' is-invalid' : '' }}" id="password" placeholder="New Password" name="password" required>
                @if ($errors->has('password'))
                    <span class="help-block">
                        <strong>{{ $errors->first('password') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <label class="control-label text-right col-sm-4" for="cpassword">Confirm Password:</label>
            <div class="col-md-8">
                <input type="password" class="form-control form-control-sm {{ $errors->has('password') ? ' is-invalid' : '' }}" id="cpassword" name="password_confirmation" placeholder="Confirm Password" required>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <label class="control-label text-right col-sm-4" for="roles">Roles:</label>
            <div class="col-md-8">
                <select class="form-control  {{ $errors->has('roles') ? ' is-invalid' : '' }} form-control-sm" id="roles" multiple="true" name="roles[]">
                    @if(isset($user))
                        @foreach($roles as $role)
                            <option value="{{$role->id}}" {{in_array($role->id,$user_role) ? 'selected' : ''}}>{{$role->name}}</option>
                        @endforeach
                    @else
                        @foreach($roles as $role)
                            <option value="{{$role->id}}">{{$role->name}}</option>
                        @endforeach
                    @endif
                </select>
                @if ($errors->has('roles'))
                    <span class="help-block">
                        <strong>{{ $errors->first('roles') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>
</div>
<!-- Permissions -->
{{--

@if(isset($user))
    @include('shared._permissions', ['closed' => 'true', 'model' => $user ])
@endif

--}}

resources/views/user/edit.blade.php
@extends('layouts.master')
@section('title', ' - Users')
@section('content_header', 'Users')
@section('content_header_link')
    @can('view_users')
        <a class="breadcrumb-item" href="{{ route('users.index') }}">List</a>
    @endcan
    @can('add_users')
        <a class="breadcrumb-item" href="{{ route('users.create') }}">Add User</a>
    @endcan
@endsection

@section('content')
<div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title">Edit</h6>
    <p class="mg-b-10 mg-sm-b-10">Edit User ID {{ str_pad($user->id,4,'0',STR_PAD_LEFT) }}</p>
    <form class="form-horizontal" action="{{route('users.update',$user->id)}}" method="POST">
        {{ method_field('PATCH') }}
        @include('user._form')
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-right col-sm-4"></label>
                    <div class="col-md-8">
                        @can('edit_users')
                            <button type="submit" name="update" value="update" class="btn btn-default btn-sm"> Update</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.master')
@section('title', ' - Users')
@section('content_header', 'Users')
@section('content_header_link')
    <span class="breadcrumb-item active">List</span>
    @can('add_users')
        <a class="breadcrumb-item" href="{{ route('users.create') }}">Add User</a>
    @endcan
@endsection
@section('content')
    <div class="card pd-20 pd-sm-40" style="min-height: 450px;">
        @include('shared._alert')
        <h6 class="card-body-title">List</h6>
        <p class="mg-b-10 mg-sm-b-10">List of registered users.</p>
        <div class="card-title mg-b-10">
            @can('print_users')
                <a href="{{route('user-print')}}" target="_blank" class="btn btn-info btn-sm pull-left">Print</a>
            @endcan
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="data-table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Role</th>
                    <th>Created At</th>
                    @can('edit_users', 'delete_users')
                    <th class="text-center">Actions</th>
                    @endcan
                </tr>
                </thead>
                <tbody>
                @foreach($result as $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->firstname }}  {{ $item->lastname }}</td>
                        <td>{{ $item->username }}</td>
                        <td>{{ $item->roles->implode('name', ', ') }}</td>
                        <td>{{ $item->created_at->toFormattedDateString() }}</td>

                        @can('edit_users')
                        <td class="text-center">
                            @include('shared._actions', [
                                'entity' => 'users',
                                'id' => $item->id
                            ])
                        </td>
                        @endcan
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{ $result->links() }}
    </div>
@endsection

resources/views/user/new.blade.php
@extends('layouts.master')
@section('title', ' - Users')
@section('content_header', 'Add User')
@section('content_header_link')
    <a class="breadcrumb-item" href="{{ route('users.index') }}">List</a>
    @can('add_users')
        <span class="breadcrumb-item active">Add User</span>
    @endcan
@endsection
@section('content')
<div class="card pd-20 pd-sm-40">
    <form class="form-horizontal" action="{{route('users.store')}}" method="POST">
        @include('user._form')
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-right col-sm-4"></label>
                    <div class="col-md-8">
                        @can('add_users')
                            <button type="submit" name="update" value="update" class="btn btn-default btn-sm"> Save</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/user/print.blade.php
<<!DOCTYPE html>
<html>
<head>
	<title>User's List</title>
</head>
<style type="text/css">
	table{
		width: 100%;
	}
	th,td{
		padding-left: 7px;
		padding-right: 7px;
	}
	h2{
		text-align: center;
	}
</style>
<body>
	<div>
		<h2>List Of Users</h2>
	</div>
	<br/>
	<table class="table table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Username</th>
                <th>Role</th>
                <th>Created At</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ ucfirst($user->firstname) }} {{ ucfirst($user->middlename) }} {{ ucfirst($user->lastname) }}</td>
                    <td>{{ $user->username }}</td>
                    <td>{{ $user->roles->implode('name', ', ') }}</td>
                    <td>{{ $user->created_at->toFormattedDateString() }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
</body>
</html>