routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Auth::check()){
    	return redirect()->route('dashboard-index');
	}
	else{
		return redirect()->route('login');
	}
});
Route::get('/form', 'StudentDirectoryController@guest_create')->name('guest_create');
Route::post('/form', 'StudentDirectoryController@guest_save')->name('guest_save');
Route::get('/response', 'StudentDirectoryController@responsepage')->name('guest_response');
Auth::routes();
Route::middleware('auth')->group(function () {
Route::middleware('appex')->group(function () {
	Route::resource('/systems/users', 'UserController');
    Route::resource('/systems/roles', 'RoleController');
    Route::resource('/systems/permissions', 'RoleController');
    Route::resource('/systems/settings', 'RoleController');
    Route::get('/systems/users/print/list','UserController@printall')->name('user-print');
    Route::get('/systems/profile', 'UserController@profile')->name('profile');
    Route::post('/systems/profile', 'UserController@updateProfile')->name('update-profile');
    Route::get('/systems/logs','UserController@logs_index')->name('logs.index');
    Route::get('/systems/logs/print','UserController@log_print')->name('logs.print');

    Route::get('/directory/{id}', 'StudentDirectoryController@index')->name('directory-index');
    Route::get('/directory/printall/{id}', 'StudentDirectoryController@printall')->name('directory-printall');
    Route::get('/directory/printid/{id}', 'StudentDirectoryController@print_id')->name('directory-print_id');
    Route::get('/directory/{id}/print/{ref_id}', 'StudentDirectoryController@print_each')->name('directory-print_each');
    Route::get('/directory/{id}/create', 'StudentDirectoryController@create')->name('directory-create');
    Route::post('/directory/{id}/create', 'StudentDirectoryController@store')->name('directory-store');
    Route::get('/directory/{id}/edit/{ref_id}', 'StudentDirectoryController@edit')->name('directory-edit');
    Route::post('/directory/{id}/edit/{ref_id}', 'StudentDirectoryController@update')->name('directory-update');

    Route::resource('/settings/courses','CoursesController');
    Route::get('/settings/courses/print/list','CoursesController@printall')->name('courses-print');


	Route::get('/search', 'HomeController@getsearch_global')->name('search-display');
	Route::get('/courses/notification/show', 'HomeController@notification')->name('notify-display');

    Route::get('/home', 'HomeController@index')->name('dashboard-index');
    Route::get('/untrack/recent', 'HomeController@recent')->name('recent-list');
    Route::post('/untrack/recent', 'HomeController@profileMany')->name('recent-many');
    Route::delete('/untrack/recent/{id}', 'HomeController@remove')->name('recent-remove');
    Route::put('/untrack/recent/{id}', 'HomeController@update')->name('recent-update');
    Route::get('/untrack/view_profile/{id}', 'HomeController@view_profile')->name('recent-view');
    Route::post('/untrack/view_profile/{id}', 'HomeController@profile')->name('recent-profile');
    Route::get('/untrack/mark/', 'HomeController@mark')->name('recent-mark');
    Route::get('/untrack/notify/btn', 'HomeController@btnnotify')->name('recent-notify');
    Route::get('/settings/sy/index', 'SchoolYearController@index')->name('sy.index');
    Route::get('/settings/sy/create', 'SchoolYearController@create')->name('sy.create');
    Route::post('/settings/sy/create', 'SchoolYearController@store')->name('sy.store');
    Route::get('/settings/sy/{id}', 'SchoolYearController@edit')->name('sy.edit');
    Route::patch('/settings/sy/{id}', 'SchoolYearController@update')->name('sy.update');

    Route::get('/search', 'HomeController@getsearch_global')->name('search');
});
});
Route::get('/places/provinces', 'PlacesController@getprovinces')->name('provinces');
Route::get('/places/citymun', 'PlacesController@getcitymun')->name('citymun');
Route::get('/places/barangays', 'PlacesController@getbarangays')->name('barangays');

resources/views/layouts/master/content_header.blade.php
<div class="row page-titles">
    <div class="col-md-5 col-8 align-self-center">
        <h3 class="text-themecolor m-b-0 m-t-0">@yield('content_header')</h3>
        <ol class="breadcrumb m-t-5">
            @yield('content_header_link')
        </ol>
    </div>
    <div class="col-md-7 col-4 align-self-center">
        <div class="d-flex m-t-10 justify-content-end">
            <div class="d-flex m-r-20 m-l-10 hidden-md-down">
                <div class="chart-text m-r-10">
                    <h6 class="m-b-0"><small>DATE</small></h6>
                    <h5 class="m-t-0 text-info">{{date('l, F d Y')}}</h5></div>
            </div>
            <div class="d-flex m-r-20 m-l-10 hidden-md-down">
                <div class="chart-text m-r-10">
                    <h6 class="m-b-0"><small>TIME</small></h6>
                    <h5 class="m-t-0 text-primary">{{date('h:i:s A')}}</h5></div>
            </div>
            <div class="">
                <button class="right-side-toggle waves-effect waves-light btn-success btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/master/leftsidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User profile -->
        <div class="user-profile" style="background: url({{ asset('assets/images/background/user-infozz.jpg') }}) no-repeat;">
            <!-- User profile image -->
            <div class="profile-img"> <img src="{{ asset('assets/images/pit-logozz.png') }}" alt="user" /> </div>
            <!-- User profile text-->
            <div class="profile-text"> <a href="#" class="dropdown-toggle u-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">{{Auth::user()->name}}</a>
                <div class="dropdown-menu animated flipInY">
                    <a href="#" class="dropdown-item"><i class="ti-user"></i> My Profile</a>
                    <a href="#" class="dropdown-item"><i class="ti-wallet"></i> Sample</a>
                    <a href="#" class="dropdown-item"><i class="ti-email"></i> Sample</a>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"><i class="ti-settings"></i> Sample</a>
                    <div class="dropdown-divider"></div> <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="dropdown-item"><i class="fa fa-power-off"></i> Logout</a>
                </div>
            </div>
        </div>
        <!-- End User profile text-->
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-small-cap">STUDENT DIRECTORY</li>
                <li {{ Request::is('home*') ? 'class=active' : '' }}>
                    <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-home"></i><span class="hide-menu">Home </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{route('dashboard-index')}}">Dashboard</a></li>
                        <li><a href="{{route('recent-list')}}">Manage Records</a></li>
                    </ul>
                </li>
                <li {{ Request::is('courses*') ? 'class=active' : '' }}> <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-laptop-windows"></i><span class="hide-menu">Courses</span></a>
                    <ul aria-expanded="false" class="collapse">
                        @foreach(App\Course::all() as $courses)
                            <li><a href="/courses/{{$courses->id}}">{{$courses->shortname}}</a></li>
                        @endforeach
                    </ul>
                </li>
                <li {{ Request::is('systems*') ? 'class=active' : '' }}>
                    <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-settings"></i><span class="hide-menu">System Properties</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('users.index') }}">Users</a></li>
                        <li><a href="{{ route('roles.index') }}">Roles and Permissions</a></li>
                        <li><a href="{{ route('settings.index') }}">Display Settings</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <!-- Bottom points-->
    <div class="sidebar-footer">
        <!-- item-->
        <a href="" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>
        <!-- item-->
        <a href="" class="link" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
        <!-- item-->
        <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>
    </div>
    <!-- End Bottom points-->
</aside>

resources/views/layouts/master/logo.blade.php
<div class="navbar-header">
    <a class="navbar-brand" href="">
        <!-- Logo icon -->
        <b>
            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
            <!-- Dark Logo icon -->
            <img src="{{ asset('assets/images/logo-icon.png') }}" alt="SDS" class="dark-logo" />
            <!-- Light Logo icon -->
            <img src="{{ asset('assets/images/logo-light-icon.png') }}" alt="SDS" class="light-logo" />
        </b>
        <!--End Logo icon -->
        <!-- Logo text -->
        <span>
             <!-- dark Logo text -->
             <img src="{{ asset('assets/images/logo-text.png') }}" alt="SDS PIT-TC" class="dark-logo" />
             <!-- Light Logo text assets/images/logo-light-text.png -->    
             <!-- <img src="" class="light-logo" alt="SDS PIT-TC" style="color:#fff;font-weight: bold" /> -->
             <span class="light-logo" style="color:#fff;font-weight: bold" >
                 SDS PIT-TC
             </span>
         </span>
    </a>
</div>

resources/views/layouts/master/preloader.blade.php
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
</div>

resources/views/layouts/master/rightsidebar.blade.php
<div class="right-sidebar">
    <div class="slimscrollright">
        <div class="rpanel-title"> Service Panel <span><i class="ti-close right-side-toggle"></i></span> </div>
        <div class="r-panel-body">
            <ul id="themecolors" class="m-t-20">
                <li><b>With Light sidebar</b></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/default.css') }}" class="default-theme">1</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/green.css') }}" class="green-theme">2</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/red.css') }}" class="red-theme">3</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/blue.css') }}" class="blue-theme working">4</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/purple.css') }}" class="purple-theme">5</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/megna.css') }}" class="megna-theme">6</a></li>
                <li class="d-block m-t-30"><b>With Dark sidebar</b></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/default-dark.css') }}" class="default-dark-theme">7</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/green-dark.css') }}" class="green-dark-theme">8</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/red-dark.css') }}" class="red-dark-theme">9</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/blue-dark.css') }}" class="blue-dark-theme">10</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/purple-dark.css') }}" class="purple-dark-theme">11</a></li>
                <li><a href="javascript:void(0)" data-theme="{{ asset('assets/material/css/colors/megna-dark.css') }}" class="megna-dark-theme ">12</a></li>
            </ul>
        </div>
    </div>
</div>

resources/views/layouts/master/toggle_item1.blade.php
<ul class="navbar-nav mr-auto mt-md-0">
    <!-- This is  -->
    <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
    <li class="nav-item"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
    <!-- ============================================================== -->
    <!-- Search -->
    <!-- ============================================================== -->
    <li class="nav-item hidden-sm-down search-box">
        <a class="nav-link hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
        <form class="app-search" method="GET" action="{{route('search-display')}}">
            <input type="text" class="form-control" required="" name="searchfield" placeholder=" S e a r c h"> <a class="srh-btn"><i class="ti-close"></i></a>
        </form>
    </li>
    <!-- ============================================================== -->
    <!-- Messages -->
    <!-- ============================================================== -->
    <li class="nav-item dropdown mega-dropdown"> <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="mdi mdi-view-grid"></i></a>
        <div class="dropdown-menu scale-up-left">
            <ul class="mega-dropdown-menu row">
                <li class="col-lg-3 col-xlg-2 m-b-30">
                    <h4 class="m-b-20">CAROUSEL</h4>
                    <!-- CAROUSEL -->
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active">
                                <div class="container"> <img class="d-block img-fluid" src="/assets/images/big/img1.jpg" alt="First slide"></div>
                            </div>
                            <div class="carousel-item">
                                <div class="container"><img class="d-block img-fluid" src="/assets/images/big/img2.jpg" alt="Second slide"></div>
                            </div>
                            <div class="carousel-item">
                                <div class="container"><img class="d-block img-fluid" src="/assets/images/big/img3.jpg" alt="Third slide"></div>
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
                    </div>
                    <!-- End CAROUSEL -->
                </li>
                <li class="col-lg-3 m-b-30">
                    <h4 class="m-b-20">ACCORDION</h4>
                    <!-- Accordian -->
                    <div id="accordion" class="nav-accordion" role="tablist" aria-multiselectable="true">
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <h5 class="mb-0">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                              Collapsible Group Item #1
                            </a>
                          </h5> </div>
                            <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                                <div class="card-block"> Anim pariatur cliche reprehenderit, enim eiusmod high. </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab" id="headingTwo">
                                <h5 class="mb-0">
                            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                              Collapsible Group Item #2
                            </a>
                          </h5> </div>
                            <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                                <div class="card-block"> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab" id="headingThree">
                                <h5 class="mb-0">
                            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                              Collapsible Group Item #3
                            </a>
                          </h5> </div>
                            <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
                                <div class="card-block"> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="col-lg-3  m-b-30">
                    <h4 class="m-b-20">CONTACT US</h4>
                    <!-- Contact -->
                    <form>
                        <div class="form-group">
                            <input type="text" class="form-control" id="exampleInputname1" placeholder="Enter Name"> </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Enter email"> </div>
                        <div class="form-group">
                            <textarea class="form-control" id="exampleTextarea" rows="3" placeholder="Message"></textarea>
                        </div>
                        <button type="submit" class="btn btn-info">Submit</button>
                    </form>
                </li>
                <li class="col-lg-3 col-xlg-4 m-b-30">
                    <h4 class="m-b-20">List style</h4>
                    <!-- List style -->
                    <ul class="list-style-none">
                        <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> You can give link</a></li>
                        <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> Give link</a></li>
                        <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> Another Give link</a></li>
                        <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> Forth link</a></li>
                        <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> Another fifth link</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </li>
    <!-- ============================================================== -->
    <!-- End Messages -->
    <!-- ============================================================== -->
</ul>

resources/views/layouts/master/toggle_item2.blade.php
<ul class="navbar-nav my-lg-0">
    <!-- ============================================================== -->
    <!-- Comment -->
    <!-- ============================================================== -->
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-muted text-muted waves-effect waves-dark notifybtn" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="mdi mdi-bell"></i>
            <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right mailbox scale-up">
            <ul>
                <li>
                    <div class="drop-title">Notifications</div>
                </li>
                <li>
                    <div class="message-center notification-display">
                    </div>
                </li>
                <li>
                    <a class="nav-link text-center" href="javascript:void(0);"> <strong>Check all notifications</strong> <i class="fa fa-angle-right"></i> </a>
                </li>
            </ul>
        </div>
    </li>
    <!-- ============================================================== -->
    <!-- End Comment -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Messages -->
    <!-- ============================================================== -->
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="mdi mdi-history"></i>
            <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
        </a>
        <div class="dropdown-menu mailbox dropdown-menu-right scale-up" aria-labelledby="2">
            <ul>
                <li>
                    <div class="drop-title">Logs</div>
                </li>
                <li>
                    <div class="message-center">
                        <!-- Message -->
                        <a href="#">
                            <div class="user-img"> <img src="/assets/images/users/1.jpg" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>
                            <div class="mail-contnet">
                                <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </div>
                        </a>
                        <!-- Message -->
                        <a href="#">
                            <div class="user-img"> <img src="/assets/images/users/2.jpg" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
                            <div class="mail-contnet">
                                <h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </div>
                        </a>
                        <!-- Message -->
                        <a href="#">
                            <div class="user-img"> <img src="/assets/images/users/3.jpg" alt="user" class="img-circle"> <span class="profile-status away pull-right"></span> </div>
                            <div class="mail-contnet">
                                <h5>Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span> </div>
                        </a>
                        <!-- Message -->
                        <a href="#">
                            <div class="user-img"> <img src="/assets/images/users/4.jpg" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span> </div>
                            <div class="mail-contnet">
                                <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </div>
                        </a>
                    </div>
                </li>
                <li>
                    <a class="nav-link text-center" href="javascript:void(0);"> <strong>See all e-Mails</strong> <i class="fa fa-angle-right"></i> </a>
                </li>
            </ul>
        </div>
    </li>
    <!-- ============================================================== -->
    <!-- End Messages -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Profile -->
    <!-- ============================================================== -->
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{ asset('assets/images/pit-logozz.png') }}" alt="user" class="profile-pic" /></a>
        <div class="dropdown-menu dropdown-menu-right scale-up">
            <ul class="dropdown-user">
                <li>
                    <div class="dw-user-box">
                        <div class="u-img"><img src="{{ asset('assets/images/pit-logozz.png') }}" alt="user"></div>
                        <div class="u-text">
                            <h4>{{Auth::user()->name}}</h4>
                            <p class="text-muted">{{Auth::user()->username}}</p><a href="" class="btn btn-rounded btn-danger btn-sm">View Profile</a></div>
                    </div>
                </li>
                <li role="separator" class="divider"></li>
                <li><a href="#"><i class="ti-user"></i> My Profile</a></li>
                <li><a href="#"><i class="ti-wallet"></i> My Balance</a></li>
                <li><a href="#"><i class="ti-email"></i> Inbox</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#"><i class="ti-settings"></i> Account Setting</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
        </div>
    </li>
</ul>